services:
  # The PostgreSQL Database Engine Container
  postgres_db:
    image: postgres:16-alpine
    container_name: stayhost_postgres
    restart: always
    environment:
      POSTGRES_USER: stayhost_admin
      POSTGRES_PASSWORD: super_secret_password_123
      POSTGRES_DB: stayhost_vault
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
